### ISSUE TITLE
Unable to compile on ubuntu 18.04 latest updates

### ISSUE THREAD

**Issue by phirestalker** [ozonesecurity/ozonebase#150]
I get a lot of errors, but the rest of them might be a domino effect. The first error is:

`/home/phire/ozonebase/server/src/base/../libimg/libimgImage.h: At global scope:
/home/phire/ozonebase/server/src/base/../libimg/libimgImage.h:276:28: error: expected identifier before numeric constant
     enum { CHAR_HEIGHT=11, CHAR_WIDTH=6 };
                            ^
`

It seems the newer gcc libraries now define a CHAR_WIDTH and CHAR_HEIGHT in the standard headers. I would just rename them, but am unsure how to find all of the references in all of the files to do so.

**Comment by phirestalker** [comment]
ok I renamed them all and then ran into another problem with compilation. it said readv and writev were undefined. On my system readv is in a file called sys/uio.h, so I added a reference to that in libgenComms.h. now I have another error that says
`/home/phire/ozoneroot/include/dlib/dnn/layers.h: In member function ‘dlib::alias_tensor_const_instance dlib::fc_<num_outputs_, bias_mode>::get_weights() const’:
/home/phire/ozoneroot/include/dlib/dnn/layers.h:1104:37: error: no match for call to ‘(const dlib::alias_tensor) (const dlib::resizable_tensor&, int)’
             return weights(params, 0);
                                     ^
`

**Comment by phirestalker** [comment]
ok I fixed the last one as well. It seems dlib in the externals directory needs to be updated to include [https://github.com/davisking/dlib/commit/4dfeb7e186dd1bf6ac91273509f687293bd4230a#diff-43ed2656f25b9b2e95a4949e1d5b37b7](url)

**Comment by pliablepixels** [comment]
Thank you for your diligence on this. Are you able to to do a PR? I don't use Ubuntu 18, but I can download a VM and check. The build process does not tag a specific release of dlib and fetches master so you should not have a need to apply a commit that old.

**Comment by phirestalker** [comment]
I am sorry, I still have not learned how to do a PR. I thought it was supposed to get master as well, I wonder what happened? If you can point me to a good tutorial on pull requests, I would be willing to try.

**Comment by pliablepixels** [comment]
[This is a good guide](https://github.com/ZoneMinder/ZoneMinder/wiki/Understanding-Github-and-Pull-Requests), you can follow it (just change the `zoneminder` repo to `ozonebase`)

**Comment by phirestalker** [comment]
here is the pull request [url](https://github.com/ozonesecurity/ozonebase/pull/151)

**Comment by phirestalker** [comment]
just compiled successfully on Ubuntu 18.04. I guess the older version of dlib was a fluke.
